### ISSUE TITLE
Activate account

### ISSUE THREAD

**Issue by joaopsoliveira03** [nei-estg/nei-website#123]
For this we need a route on react that sends the code to the db.
If the db response is good we show that the account is confirmated and add a button to login otherwise show some error like invalid link

**Comment by heyliceeee** [comment]
- [ ] send an email the user, informing whether their email is associated with a student or not. If it is associated with a student, the backend activates the account, otherwise, you have to contact the NEI.
- [ ] after NEI is contacted by the user, it can activate their account.
- [ ] after the user receives an email informing whether their email is associated with a student or not, they receive a code. You will then be redirected to a page where you will enter your username and the code received.
